#!/bin/bash

# backup vimrc
if [ -s ~/.vimrc ]; then
  cp ~/.vimrc ~/.vimrc.bak
fi

# This script actually does a ton of stuff... So just use it :3
bash <(curl -sL https://git.io/haskell-vim-now)

# copy new vimrc
cp .vimrc ~/

echo "In vim, run :PlugInstall to complete installation."
echo "If you want a different iTerm2 color scheme, go here:"
echo "https://github.com/mbadolato/iTerm2-Color-Schemes"
echo "I like chalk."
echo "If you want a new typeface, try Input Mono."
echo "http://input.fontbureau.com/"
echo "Enjoy!"
